import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Indicator } from "@/components/theme/indicator";
import { Provider } from "@/components/theme/provider";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { Header } from "@/components/header/header";
import { Authentication } from "@/components/authen/authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Preview",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/logo.png",
    apple: "/logo.png"
  }
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  interactiveWidget: 'resizes-visual',
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Provider attribute="class" defaultTheme="system" enableSystem>
          <main className="flex min-h-screen flex-col w-screen bg-muted/30">
            <Authentication>
              {children}
              <Indicator />
            </Authentication>
          </main>
        </Provider>
      </body>
    </html>
  );
}
